### ISSUE TITLE
can we get some benchmarks?

### ISSUE THREAD

**Issue by divinity76** [nazar-pc/blake2.wasm#1]
just to get some rough idea of what performance to expect, 
for example, is it comparable to https://github.com/dcposch/blakejs ?

> BLAKE2b: 15.2 MB / second 
> BLAKE2s: 20.4 MB / second
> on a 2.2GHz i7-4770HQ

or is it significantly faster than that?

**Comment by nazar-pc** [comment]
There are some numbers from my testing here:  https://github.com/dcposch/blakejs/pull/7
But as usual, with newer versions of browser engines and on different hardware results will be different.
In general, you can expect up to a magnitude faster hashing depending on use case.
