### ISSUE TITLE
Callback is never called

### ISSUE THREAD

**Issue by amjha** [nazar-pc/blake2.wasm#2]
I am trying to use this in my ReactJS application. However the code inside ` blake2.ready(function () {})` is never called. Here is my code that is loaded inside FileReader API load event.
```javascript
           const blake2 = require('blake2.wasm');
           blake2.ready(function () {
                console.log('Hash started');
                blake2.Blake2b(64, null);
                blake2.Blake2b.update(new Uint8Array(reader.result));
                const hash = blake2.Blake2b.final();
                self.setState({hashedName: `blake2b:${hash}`});
                console.log(hash);
            });
```

**Comment by nazar-pc** [comment]
There is likely an issue with WASM file loading. Make sure it is located where your JS bundle is and also make sure it is actually called right after file load or else `document.currentScript` will point to the wrong location and it will not actually be able to load WASM file automatically.

Network tab in dev tools should give you the answer to where it looks for WASM file.

**Comment by amjha** [comment]
There appears to be an issue with loading WASM file in webpack 4.  https://github.com/webpack/webpack/issues/6725

I tried this with plain `nodejs` app and it seems to work. It would be nice to have a `blake2bHex()` to get hex string. But I guess that would be a separate issue.
